// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6QGw2x5TQJEpX2QAO77Tvth1OfZCCLms',
    appId: '1:1018408908061:web:c3fb177dba9623af0a5df4',
    messagingSenderId: '1018408908061',
    projectId: 'kublian',
    authDomain: 'kublian.firebaseapp.com',
    storageBucket: 'kublian.firebasestorage.app',
    measurementId: 'G-HH9QMYVJ7J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBalJX_JV-GlRXfsKilfcjPDJNAkRKMuS4',
    appId: '1:1018408908061:android:0d5d90789cf8c4830a5df4',
    messagingSenderId: '1018408908061',
    projectId: 'kublian',
    storageBucket: 'kublian.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1s0ZWGWulA0WHo5Od_4L2r2lvEdxNPts',
    appId: '1:1018408908061:ios:4937646212b4fa030a5df4',
    messagingSenderId: '1018408908061',
    projectId: 'kublian',
    storageBucket: 'kublian.firebasestorage.app',
    androidClientId:
        '1018408908061-feikbd3r37kihd3g8ngoh5n3e0jihjcg.apps.googleusercontent.com',
    iosClientId:
        '1018408908061-820q8jifggkcadftqt874tk4carpkpi8.apps.googleusercontent.com',
    iosBundleId: 'com.example.kublian',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1s0ZWGWulA0WHo5Od_4L2r2lvEdxNPts',
    appId: '1:1018408908061:ios:4937646212b4fa030a5df4',
    messagingSenderId: '1018408908061',
    projectId: 'kublian',
    storageBucket: 'kublian.firebasestorage.app',
    androidClientId:
        '1018408908061-feikbd3r37kihd3g8ngoh5n3e0jihjcg.apps.googleusercontent.com',
    iosClientId:
        '1018408908061-820q8jifggkcadftqt874tk4carpkpi8.apps.googleusercontent.com',
    iosBundleId: 'com.example.kublian',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD6QGw2x5TQJEpX2QAO77Tvth1OfZCCLms',
    appId: '1:1018408908061:web:ba497970739a6c450a5df4',
    messagingSenderId: '1018408908061',
    projectId: 'kublian',
    authDomain: 'kublian.firebaseapp.com',
    storageBucket: 'kublian.firebasestorage.app',
    measurementId: 'G-KVZJM9Q0CC',
  );
}
